name: Rust

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --features sdl2_mac --verbose
    - name: Run tests
      run: cargo test  --features sdl2_mac --verbose
